# Generated by Django 6.0.3 on 2026-03-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('mode_of_enquiry', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=100)),
                ('enquiry_date', models.DateField()),
                ('address', models.TextField()),
                ('enquiry_handled_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_not_to_join', models.TextField(blank=True, null=True)),
                ('educational', models.CharField(max_length=100)),
            ],
        ),
    ]
