# Generated by Django 6.0.3 on 2026-03-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='Student_Name',
            new_name='student_name',
        ),
    ]
