# Generated by Django 6.0.3 on 2026-03-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_rename_student_name_administrator_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='educational',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='email',
            field=models.EmailField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='enquiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='enquiry_handled_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='mode_of_enquiry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
